# Generated by Django 3.1.3 on 2020-11-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='image',
            field=models.ImageField(default='placeholder.jpg', upload_to='upload/'),
        ),
    ]
