# Generated by Django 3.1.3 on 2020-11-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hero', '0002_auto_20201116_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='image',
            field=models.CharField(max_length=80),
        ),
    ]
